#!/usr/bin/env bash
# Bash script to configure a new Ubuntu machine with Nginx
sudo apt update && upgrade
sudo apt install nginx -y 
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
