#!/usr/bin/env bash
# Bash script to configure a new Ubuntu machine with Nginx
sudo apt-get update
sudo apt-get install nginx -y
# Creating index.html page
echo "Holberton School" | sudo tee /var/www/html/index.html

# Checking if Nginx is running
state=$(pgrep nginx)

if [ -n "$state" ]; then
  # Restarting Nginx if it's already running
  sudo service nginx restart
else
  # Starting Nginx if it's not running
  sudo service nginx start
fi

# Verifying Nginx status
nginx_status=$(curl -s http://localhost)

# Checking if Nginx is returning 200
if [[ $nginx_status -eq 200 ]]; then
  echo "Nginx is returning 200"
else
  echo "Nginx is not returning 200"
fi
